export interface PasangBaru {
  id: number;
  tglrab: string;
  no_rab: string;
  reg_id: number;
  keterangan: null;
  biaya_peralatan: number;
  biaya_ongkos: number;
  biaya_lainnya: number;
  biaya_jl: number;
  biaya_survey: number;
  diskon: number;
  ppn: number;
  total: number;
  user_input: number;
  flagsetuju: number;
  flagangsur: number;
  flaglunas: number;
  group_id: number;
  uangmuka: number;
  angsurkali: number;
  angsuranperbulan: number;
  no_pelanggan: null | string;
  user_setuju: null | number;
  golongan_id: number;
  flagsudahpasang: number;
  tglpasang: null;
  petugas_id: null;
  flagrealisasi: number;
  user_realisasi: null;
  tglrealisasi: null;
  realisasi_periode: null;
  stan: number;
  created_at: string;
  updated_at: string;
  flagditugasi: number;
  merek_id: null;
  nama_merek: null;
  nometer: null;
  nama_realisasi: null;
  nama_petugas_pasang: null;
  diameter_id: number;
  nama_diameter: string;
  tglsetuju: null | string;
  nama: string;
  alamat: string;
  golongan: string;
  no_regis: string;
  is_mbr: number;
  tenor: number;
  periode: string;
  tmp_lahir: string;
  tgl_lahir: string;
  no_ktp: string;
  no_kk: string;
  no_telp: string;
  no_hp: string;
  email: string;
  pekerjaan: string;
  jumlah_penghuni: number;
  jenis_bangunan: string;
  kepemilikan: string;
  kec_id: number;
  kel_id: number;
  wilayah_id: number;
  rayon_id: number;
  jalan_id: number;
  flagpajak: number;
  kecamatan: string;
  kelurahan: string;
  wilayah: string;
  rayon: string;
  jalan: string;
  koderayon: string;
  kode_golongan: string;
  nama_golongan: string;
}

export interface PelangganPasangBaru {
  id: number;
  pendaftaranpel_id: number;
  no_regis: string;
  nama: string;
  alamat: string;
  is_mbr: number;
}
